---
format_version: '23'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other

# Trigger toolsetup just to have mise in $PATH
tools:
  nodejs: 22:installed
tool_config:
  provider: mise

pipelines:
  validate-index:
    workflows:
      validate-index-mac: {}
      validate-index-linux: {}

step_bundles:
  install-nix:
    steps:
    - script@1:
        title: Install Nix
        # TODO: temporary until stacks have Nix preinstalled
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -eo pipefail

            export NIX_INSTALLER_NO_CONFIRM=true
            export NIX_INSTALLER_ENABLE_FLAKES=true
            curl -sSf -L https://install.lix.systems/lix | sh -s -- install

            echo "access-tokens = github.com=$NIX_GITHUB_TOKEN" | sudo tee -a /etc/nix/nix.conf

            # Reload daemon after nix.conf file changes
            sudo launchctl kickstart -k system/org.nixos.nix-daemon || true
  validate-index:
    steps:
    - script@1:
        title: Validate index
        inputs:
        - content: |-
            set -eo pipefail
            cd nixpkgs-index
            . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
            mise exec uv -- uv run nixpkgs-index validate --config example-config.yml --index nixpkgs-index.yml
  create-index-update-pr:
    steps:
    - script@1:
        title: Run incremental index update
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            cd nixpkgs-index
            . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
            mise exec uv -- uv run nixpkgs-index index \
              --config example-config.yml \
              --output nixpkgs-index.yml \
              --step-interval 1d \
              --max-steps 7
    - script@1:
        title: Create PR if index changed
        inputs:
        - content: |-
            #!/bin/bash
            set -e
            cd nixpkgs-index

            if git diff --quiet nixpkgs-index.yml; then
              echo "No changes detected in index file"
              exit 0
            fi

            echo "Changes detected in index file"

            if [ -z "$GITHUB_INDEX_UPDATER_TOKEN" ]; then
              echo "ERROR: GITHUB_INDEX_UPDATER_TOKEN environment variable not set"
              echo "Please add GITHUB_INDEX_UPDATER_TOKEN to Bitrise secrets"
              exit 1
            fi

            BRANCH_NAME="nixpkgs-index-update-$(date -u +%Y%m%d-%H%M%S)"
            git checkout -b "$BRANCH_NAME"

            git add nixpkgs-index.yml
            git commit -m "chore: update nixpkgs index" -m "Automated index update from nixpkgs latest commits."
            git push origin "$BRANCH_NAME"

            GH_TOKEN="$GITHUB_INDEX_UPDATER_TOKEN" gh pr create \
              --title "Scheduled nixpkgs index update: $(date -u +%Y%m%d-%H%M%S)" \
              --body "Automated incremental update of the nixpkgs index with latest package versions." \
              --head "$BRANCH_NAME" \
              --base main

workflows:
  primary:
    triggers:
        push:
        - branch: main
        pull_request:
        - source_branch: "*"
    steps:
    - git-clone@8: {}
    - script@1:
        title: Upgrade mise
        # TODO: temporary until we ship a more recent mise version with full Lua support
        inputs:
        - content: mise self-update
    - script@1:
        title: Lint
        inputs:
        - content: mise run lint
    - bundle::install-nix: {}
    - script@1:
        title: Basic plugin test
        inputs:
        - content: |-
            set -exo pipefail

            mise settings experimental=true
            . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

            mise run test
    - deploy-to-bitrise-io@2: {}
  validate-index-mac:
    meta:
      bitrise.io:
        stack: osx-xcode-edge
        machine_type_id: g2.mac.large
    steps:
    - git-clone@8: {}
    - bundle::install-nix: {}
    - bundle::validate-index: {}
  validate-index-linux:
    meta:
      bitrise.io:
        stack: ubuntu-noble-24.04-bitrise-2025-android
        machine_type_id: g2.linux.large
    steps:
    - git-clone@8: {}
    - bundle::install-nix: {}
    - bundle::validate-index: {}
  scheduled-index-update:
    steps:
    - git-clone@8: {}
    - bundle::install-nix: {}
    - bundle::create-index-update-pr: {}
meta:
  bitrise.io:
    stack: osx-xcode-26.1.x-edge
    machine_type_id: g2.mac.large
