---
format_version: '23'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other

app:
  envs:
    - INDEX_CONFIG_PATH: $BITRISE_SOURCE_DIR/nixpkgs-index-config.yml
    - INDEX_PATH: $BITRISE_SOURCE_DIR/nixpkgs-index.json

meta:
  bitrise.io:
    stack: ubuntu-noble-24.04-bitrise-2025-android
    machine_type_id: g2.linux.large

# Trigger toolsetup just to have mise in $PATH
tools:
  nodejs: 22:installed
tool_config:
  provider: mise

pipelines:
  validate-index:
    status_report_name: Validate nixpkgs index
    triggers:
      pull_request:
      - changed_files: nixpkgs-index.json
    workflows:
      validate-index-mac: {}
      validate-index-linux: {}
  checks:
    status_report_name: Checks
    triggers:
      push:
      - branch: main
      pull_request:
      - source_branch: "*"
    workflows:
      check: {}
      # TODO: disable Linux tests until we figure out glibc issues and native gems
      # integration-tests-linux-edge:
      #   depends_on: [ check ]
      # integration-tests-linux-stable:
      #   depends_on: [ check ]
      integration-tests-darwin-edge:
        depends_on: [ check ]
      integration-tests-darwin-stable:
        depends_on: [ check ]

step_bundles:
  install-nix:
    steps:
    - script@1:
        title: Install Nix
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -eo pipefail
            echo "access-tokens = github.com=$NIX_GITHUB_TOKEN" | sudo tee -a /etc/nix/nix.conf

            # Reload daemon after nix.conf file changes
            sudo launchctl kickstart -k system/org.nixos.nix-daemon || true
  integration-tests:
    steps:
    - git-clone@8: {}
    - bundle::install-nix: {}
    - script@1:
        title: Integration Tests
        inputs:
        - content: |-
            set -exo pipefail
            # mise ERROR custom backends is experimental. Enable it with `mise settings experimental=true`
            mise settings experimental=true
            mise run test-integration
  validate-index:
    steps:
    - script@1:
        title: Validate index
        inputs:
        - content: |-
            set -eo pipefail
            mise exec --cd nixpkgs-index uv -- \
              uv run nixpkgs-index validate \
                --config $INDEX_CONFIG_PATH \
                --index $INDEX_PATH
  create-index-update-pr:
    steps:
    - script@1:
        title: Run incremental index update
        inputs:
        - content: |-
            #!/bin/bash
            set -e
            export GITHUB_TOKEN=$GITHUB_API_TOKEN
            mise exec --cd nixpkgs-index uv -- uv run nixpkgs-index index \
              --config $INDEX_CONFIG_PATH \
              --output $INDEX_PATH \
              --format json \
              --step-interval 1d \
              --max-steps 7
    - script@1:
        title: Create PR if index changed
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            if git diff --quiet $INDEX_PATH; then
              echo "No changes detected in index file"
              exit 0
            fi

            echo "Changes detected in index file"

            if [ -z "$GITHUB_INDEX_UPDATER_TOKEN" ]; then
              echo "ERROR: GITHUB_INDEX_UPDATER_TOKEN environment variable not set"
              echo "Please add GITHUB_INDEX_UPDATER_TOKEN to Bitrise secrets"
              exit 1
            fi

            BRANCH_NAME="nixpkgs-index-update-$(date -u +%Y%m%d-%H%M%S)"
            git checkout -b "$BRANCH_NAME"
            git add $INDEX_PATH
            git commit -m "Automated index update from nixpkgs latest commits."
            
            REPO_URL=$(git config --get remote.origin.url)
            # Remove https:// prefix if present
            REPO_URL=$(echo "$REPO_URL" | sed 's/https:\/\///')
            git push "https://${GITHUB_INDEX_UPDATER_TOKEN}@${REPO_URL}" "$BRANCH_NAME"

            GH_TOKEN="$GITHUB_INDEX_UPDATER_TOKEN" gh pr create \
              --title "Scheduled nixpkgs index update: $(date -u +%Y-%m-%d)" \
              --body "Automated incremental update of the nixpkgs index with latest package versions." \
              --head "$BRANCH_NAME" \
              --base main

workflows:
  check:
    steps:
    - git-clone@8: {}
    - script@1:
        title: Lint
        inputs:
        - content: mise run lint
    - script@1:
        title: Unit Tests
        inputs:
        - content: mise run test-unit
    - deploy-to-bitrise-io@2: {}
  integration-tests-linux-edge:
    meta:
      bitrise.io:
        stack: ubuntu-noble-24.04-bitrise-2025-android
    steps:
    - bundle::integration-tests: {}
  integration-tests-linux-stable:
    meta:
      bitrise.io:
        stack: linux-docker-android-22.04
    steps:
    - bundle::integration-tests: {}
  integration-tests-darwin-edge:
    meta:
      bitrise.io:
        stack: osx-xcode-edge
        machine_type_id: g2.mac.x-large
    steps:
    - bundle::integration-tests: {}
  integration-tests-darwin-stable:
    meta:
      bitrise.io:
        stack: osx-xcode-latest-stable
        machine_type_id: g2.mac.x-large
    steps:
    - bundle::integration-tests: {}
  validate-index-mac:
    meta:
      bitrise.io:
        stack: osx-xcode-edge
        machine_type_id: g2.mac.large
    steps:
    - git-clone@8: {}
    - bundle::install-nix: {}
    - bundle::validate-index: {}
  validate-index-linux:
    meta:
      bitrise.io:
        stack: ubuntu-noble-24.04-bitrise-2025-android
        machine_type_id: g2.linux.large
    steps:
    - git-clone@8: {}
    - bundle::install-nix: {}
    - bundle::validate-index: {}
  scheduled-index-update:
    steps:
    - git-clone@8: {}
    - bundle::install-nix: {}
    - bundle::create-index-update-pr: {}
